# Generated by Django 5.1.1 on 2024-09-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
