# Generated by Django 5.1.1 on 2024-09-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('name', models.CharField(help_text='Введите название категории', max_length=30, verbose_name='Наименование')),
            ],
        ),
    ]
