# Generated by Django 5.1.1 on 2024-09-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0003_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to='subcategory/', verbose_name='Картинка')),
                ('name', models.CharField(help_text='Введите наименование', max_length=30, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, unique=True)),
                ('associated_category', models.ForeignKey(help_text='Выберете категорию', on_delete=django.db.models.deletion.CASCADE, related_name='related_category', to='marketApp.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['name'],
            },
        ),
    ]
