# Generated by Django 5.1.1 on 2024-09-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0004_alter_category_options_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to='category/'),
        ),
    ]
