# Generated by Django 5.1.1 on 2024-09-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0008_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='image_large',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='products/large/', verbose_name='Изображение (большое)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='products/medium/', verbose_name='Изображение (среднее)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='products/small/', verbose_name='Изображение (маленькое)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите стоимость', max_digits=10, verbose_name='Стоимость'),
        ),
    ]
